### ISSUE TITLE
Considerar nas métricas o tipo de documento data-article como citável.

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/articles_meta#183]
Em [SPS 1.9](https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-article.html#elemento-article) temos o tipo de documento data-article,

data-article:
Artigo de dados - Descreve uma coleção de conjunto de dados de pesquisa. Este tipo de publicação explica os métodos de obtenção/coleta dos dados, bem como à descrição dos ativos que compõem um conjunto de dados, sua estrutura e formato.

Demanda de computar 'data-article' como documento citável em ElasticSearch, Kibana, Analytics e demais.

relacionar com https://github.com/scieloorg/scielo_publishing_schema/issues/834

Repositórios que precisam desse ajuste: 

- [x] scieloorg/analytics - https://github.com/scieloorg/analytics/issues/143
- [x] scieloorg/xylose - https://github.com/scieloorg/xylose/issues/189
- [x] scieloorg/publicationstatsapi - https://github.com/scieloorg/publicationstatsapi/issues/4
- [ ] scieloorg/processing - https://github.com/scieloorg/processing/issues/44
- [ ] scieloorg/search-journals-proc - https://github.com/scieloorg/search-journals-proc/issues/3
- [ ] scieloorg/search-journals - https://github.com/scieloorg/search-journals/issues/495
- [x] scieloorg/PC-Programs - https://github.com/scieloorg/PC-Programs/issues/3185

**Comment by robertatakenaka** [comment]
O campo `v71` pôde ser criado no registro do tipo `c` a partir do XML, seu conteúdo é proveniente de `element-citation/@publication-type` (https://jats.nlm.nih.gov/publishing/tag-library/1.3d1/attribute/publication-type.html). Mas não necessariamente todos os registros gerados a partir de XML tem este campo criado.

Desta forma, deve-se alterar o código a seguir para considerar o `v71` com precedência.

https://github.com/scieloorg/xylose/blob/56ea916556da5fd743b2c2105247d98a72c79314/xylose/scielodocument.py#L2656

**Comment by ednilson** [comment]
@robertatakenaka  @gustavofonseca 
Considerem também as partes que descrevem dados:
Exemplo: este gráfico descreve os tipos citáveis:
https://analytics.scielo.org/w/publication/article_by_publication_year#received-granted-and-self-citing
O código que contém a mensagem em "About the chart" está aqui (observer que são 4 idiomas)
https://github.com/scieloorg/analytics/blob/master/analytics/locale/analytics.pot#L761
Utiliza-se o utilitário Babel para compilar.
http://babel.pocoo.org/en/latest/index.html

Considerar também:
https://github.com/scieloorg/xylose/blob/master/xylose/choices.py#L54
https://github.com/scieloorg/PC-Programs/blob/master/src/scielo/bin/xml/modules/attributes.py
https://github.com/scieloorg/search-journals/blob/master/iahx/locale/en/texts.ini#L352

**Comment by jamilatta** [comment]
Repositórios que precisam desse ajuste: 

- [ ] scieloorg/publicationstatsapi
- [ ] scieloorg/processing
- [ ] scieloorg/search-journals-proc
- [ ] scieloorg/search-journals
- [ ] scieloorg/analytics
- [ ] scieloorg/xylose 
- [ ] scieloorg/PC-Programs

**Comment by ednilson** [comment]
Abrir issues nos repositórios identificados.
